name: publish to github packages

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "maven"
          cache-dependency-path: "pom.xml"
      - run: mvn versions:set -DnewVersion=$(git rev-parse HEAD)
      - run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
